In [1]:
import pandas as pd

df_heart = pd.read_csv('../S03_Pré_processamento/df_heart_modified.csv')
df_heart.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Continent,Hemisphere,Heart Attack Risk,Systolic,Diastolic,Cardiac_Risk_Index,BMI_Category,Healthy_Lifestyle,Mean_Blood_Pressure,Age_Group
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,South America,Southern Hemisphere,0,158,88,199.850247,Obesidade,0,123.0,Idoso
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,North America,Northern Hemisphere,0,165,93,257.338995,Sobrepeso,0,129.0,Jovem
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,Europe,Northern Hemisphere,0,174,99,338.635314,Sobrepeso,0,136.5,Jovem
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,North America,Northern Hemisphere,0,163,100,300.192941,Obesidade,0,131.5,Idoso
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,Asia,Northern Hemisphere,0,91,88,218.761829,Normal,0,89.5,Idoso