In [ ]:
# pip install openpyxl

### S03T03 - Transformar variáveis categóricas em numéricas (one-hot encoding, label encoding, etc.).

In [101]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [102]:
# Carregar o dataset
df_heart = pd.read_csv("heart_attack_prediction_dataset.csv")
df_heart.head()

  Patient ID  Age     Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  Family History  Smoking  Obesity  Alcohol Consumption  Exercise Hours Per Week       Diet  Previous Heart Problems  Medication Use  Stress Level  Sedentary Hours Per Day  Income        BMI  Triglycerides  Physical Activity Days Per Week  Sleep Hours Per Day    Country      Continent           Hemisphere  Heart Attack Risk
0    BMW7812   67    Male          208         158/88          72         0               0        1        0                    0                 4.168189    Average                        0               0             9                 6.615001  261404  31.251233            286                                0                    6  Argentina  South America  Southern Hemisphere                  0
1    CZE1114   21    Male          389         165/93          98         1               1        1        1                    1                 1.813242  Unhealthy                        1               0             1                 4.963459  285768  27.194973            235                                1                    7     Canada  North America  Northern Hemisphere                  0
2    BNI9906   21  Female          324         174/99          72         1               0        0        0                    0                 2.078353    Healthy                        1               1             9                 9.463426  235282  28.176571            587                                4                    4     France         Europe  Northern Hemisphere                  0
3    JLN3497   84    Male          383        163/100          73         1               1        1        0                    1                 9.828130    Average                        1               0             9                 7.648981  125640  36.464704            378                                3                    4     Canada  North America  Northern Hemisphere                  0
4    GFO8847   66    Male          318          91/88          93         1               1        1        1                    0                 5.804299  Unhealthy                        1               0             6                 1.514821  160555  21.809144            231                                1                    5   Thailand           Asia  Northern Hemisphere                  0

In [103]:
# Verificando os nomes das colunas
print(df_heart.columns)  # Exibe todas as colunas do DataFrame

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure', 'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week', 'Diet', 'Previous Heart Problems', 'Medication Use', 'Stress Level', 'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides', 'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country', 'Continent', 'Hemisphere', 'Heart Attack Risk'], dtype='object')

In [104]:
# Identificando as colunas categóricas restantes
colunas_label_encoding = ['Sex', 'Hemisphere']  # Colunas com poucas categorias
colunas_label_encoding

['Sex', 'Hemisphere']

In [105]:
# 1. Aplicando Label Encoding para colunas com poucas categorias
labelencoder = LabelEncoder()
for coluna in colunas_label_encoding:
    df_heart[coluna] = labelencoder.fit_transform(df_heart[coluna])
df_heart.head()

  Patient ID  Age  Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  Family History  Smoking  Obesity  Alcohol Consumption  Exercise Hours Per Week       Diet  Previous Heart Problems  Medication Use  Stress Level  Sedentary Hours Per Day  Income        BMI  Triglycerides  Physical Activity Days Per Week  Sleep Hours Per Day    Country      Continent  Hemisphere  Heart Attack Risk
0    BMW7812   67    1          208         158/88          72         0               0        1        0                    0                 4.168189    Average                        0               0             9                 6.615001  261404  31.251233            286                                0                    6  Argentina  South America           1                  0
1    CZE1114   21    1          389         165/93          98         1               1        1        1                    1                 1.813242  Unhealthy                        1               0             1                 4.963459  285768  27.194973            235                                1                    7     Canada  North America           0                  0
2    BNI9906   21    0          324         174/99          72         1               0        0        0                    0                 2.078353    Healthy                        1               1             9                 9.463426  235282  28.176571            587                                4                    4     France         Europe           0                  0
3    JLN3497   84    1          383        163/100          73         1               1        1        0                    1                 9.828130    Average                        1               0             9                 7.648981  125640  36.464704            378                                3                    4     Canada  North America           0                  0
4    GFO8847   66    1          318          91/88          93         1               1        1        1                    0                 5.804299  Unhealthy                        1               0             6                 1.514821  160555  21.809144            231                                1                    5   Thailand           Asia           0                  0

In [106]:
#aplicando o One-Hot Encoding em outras colunas categóricas ainda não tratadas
colunas_one_hot_encoding = ['Diet', 'Smoking', 'Previous Heart Problems', 'Medication Use', 'Stress Level']  
colunas_one_hot_encoding

['Diet',
 'Smoking',
 'Previous Heart Problems',
 'Medication Use',
 'Stress Level']

In [107]:
df_heart = pd.get_dummies(df_heart, columns=colunas_one_hot_encoding, drop_first=True)
df_heart

     Patient ID  Age  Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  Family History  Obesity  Alcohol Consumption  Exercise Hours Per Week  Sedentary Hours Per Day  Income        BMI  Triglycerides  Physical Activity Days Per Week  Sleep Hours Per Day         Country      Continent  Hemisphere  Heart Attack Risk  Diet_Healthy  Diet_Unhealthy  Smoking_1  Previous Heart Problems_1  Medication Use_1  Stress Level_2  Stress Level_3  Stress Level_4  Stress Level_5  Stress Level_6  Stress Level_7  Stress Level_8  Stress Level_9  Stress Level_10
0       BMW7812   67    1          208         158/88          72         0               0        0                    0                 4.168189                 6.615001  261404  31.251233            286                                0                    6       Argentina  South America           1                  0         False           False       True                      False             False           False           False           False           False           False           False           False            True            False
1       CZE1114   21    1          389         165/93          98         1               1        1                    1                 1.813242                 4.963459  285768  27.194973            235                                1                    7          Canada  North America           0                  0         False            True       True                       True             False           False           False           False           False           False           False           False           False            False
2       BNI9906   21    0          324         174/99          72         1               0        0                    0                 2.078353                 9.463426  235282  28.176571            587                                4                    4          France         Europe           0                  0          True           False      False                       True              True           False           False           False           False           False           False           False            True            False
3       JLN3497   84    1          383        163/100          73         1               1        0                    1                 9.828130                 7.648981  125640  36.464704            378                                3                    4          Canada  North America           0                  0         False           False       True                       True             False           False           False           False           False           False           False           False            True            False
4       GFO8847   66    1          318          91/88          93         1               1        1                    0                 5.804299                 1.514821  160555  21.809144            231                                1                    5        Thailand           Asia           0                  0         False            True       True                       True             False           False           False           False           False            True           False           False           False            False
...         ...  ...  ...          ...            ...         ...       ...             ...      ...                  ...                      ...                      ...     ...        ...            ...                              ...                  ...             ...            ...         ...                ...           ...             ...        ...                        ...               ...             ...             ...             ...             ...             ...             ...             ...             ...              ...
8758    MSV9918   60    1          121          94/76          61         1               1        0                    1                 7.917342                10.806373  235420  19.655895             67                                7                    7        Thailand           Asia           0                  0          True           False       True                       True              True           False           False           False           False           False           False            True           False            False
8759    QSV6764   28    0          120        157/102          73         1               0        1                    0                16.558426                 3.833038  217881  23.993866            617                                4                    9          Canada  North America           0                  0          True           False      False                      False             False           False           False           False           False           False           False            True           False            False
8760    XKA5925   47    1          250         161/75         105         0               1        1                    1                 3.148438                 2.375214   36998  35.406146            527                                4                    4          Brazil  South America           1                  1         False           False       True                       True             False           False           False           False            True           False           False           False           False            False
8761    EPE6801   36    1          178         119/67          60         1               0        0                    0                 3.789950                 0.029104  209943  27.294020            114                                2                    8          Brazil  South America           1                  0         False            True       True                       True              True           False           False           False            True           False           False           False           False            False
8762    ZWN9666   25    0          356         138/67          75         1               1        0                    1                18.081748                 9.005234  247338  32.914151            180                                7                    4  United Kingdom         Europe           0                  1          True           False      False                      False             False           False           False           False           False           False           False            True           False            False

[8763 rows x 35 columns]

In [108]:
df_heart.columns

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure', 'Heart Rate', 'Diabetes', 'Family History', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week', 'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides', 'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country', 'Continent', 'Hemisphere', 'Heart Attack Risk', 'Diet_Healthy', 'Diet_Unhealthy', 'Smoking_1', 'Previous Heart Problems_1', 'Medication Use_1', 'Stress Level_2', 'Stress Level_3', 'Stress Level_4', 'Stress Level_5', 'Stress Level_6', 'Stress Level_7', 'Stress Level_8', 'Stress Level_9', 'Stress Level_10'], dtype='object')

In [115]:
# Atualize a lista de colunas a serem codificadas, excluindo as colunas já codificadas
colunas_one_hot_encoding = [
    'Diet_Unhealthy',  # Caso você tenha uma coluna 'Diet' que não tenha sido codificada
    'Smoking_1',  # Se houver uma coluna 'Smoking' sem o sufixo '_1'
    'Previous Heart Problems_1',  # Se não houver uma coluna codificada para isso
    'Medication Use_1',  # Caso não tenha sido codificada ainda
    'Stress Level_10'  # Se houver uma coluna sem o sufixo '_2', '_3', etc.
]

# Aplicar o one-hot encoding nas colunas ajustadas
df_heart = pd.get_dummies(df_heart, columns=colunas_one_hot_encoding, drop_first=True)

# Verifique o resultado
print(df_heart.columns)

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure', 'Heart Rate', 'Diabetes', 'Family History', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week', 'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides', 'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country', 'Continent', 'Hemisphere', 'Heart Attack Risk', 'Diet_Healthy', 'Stress Level_2', 'Stress Level_3', 'Stress Level_4', 'Stress Level_5', 'Stress Level_6', 'Stress Level_7', 'Stress Level_8', 'Stress Level_9', 'Diet_Unhealthy_True', 'Smoking_1_True', 'Previous Heart Problems_1_True', 'Medication Use_1_True', 'Stress Level_10_True'], dtype='object')

In [110]:
# Verificando o resultado final
print(df_heart.info())  # Informações sobre o DataFrame
print(df_heart.head())  # Primeiras 5 linhas após a transformação

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   int64
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Obesity                          8763 non-null   int64
 9   Alcohol Consumption              8763 non-null   int64
 10  Exercise Hours Per Week          8763 non-null   float64
 11  Sedentary Hours Per Day          8763 non-null   float64
 12  Income                           8763 non-null   int64
 13  BMI                              8763 non-null   float64
 14  Triglycerides                    8763 non-null   int64
 15  Physical Activity Days Per Week  8763 non-null   int64
 16  Sleep Hours Per Day              8763 non-null   int64
 17  Country                          8763 non-null   object
 18  Continent                        8763 non-null   object
 19  Hemisphere                       8763 non-null   int64
 20  Heart Attack Risk                8763 non-null   int64
 21  Diet_Healthy                     8763 non-null   bool
 22  Diet_Unhealthy                   8763 non-null   bool
 23  Smoking_1                        8763 non-null   bool
 24  Previous Heart Problems_1        8763 non-null   bool
 25  Medication Use_1                 8763 non-null   bool
 26  Stress Level_2                   8763 non-null   bool
 27  Stress Level_3                   8763 non-null   bool
 28  Stress Level_4                   8763 non-null   bool
 29  Stress Level_5                   8763 non-null   bool
 30  Stress Level_6                   8763 non-null   bool
 31  Stress Level_7                   8763 non-null   bool
 32  Stress Level_8                   8763 non-null   bool
 33  Stress Level_9                   8763 non-null   bool
 34  Stress Level_10                  8763 non-null   bool
dtypes: bool(14), float64(3), int64(14), object(4)
memory usage: 1.5+ MB
None
  Patient ID  Age  Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  Family History  Obesity  Alcohol Consumption  Exercise Hours Per Week  Sedentary Hours Per Day  Income        BMI  Triglycerides  Physical Activity Days Per Week  Sleep Hours Per Day    Country      Continent  Hemisphere  Heart Attack Risk  Diet_Healthy  Diet_Unhealthy  Smoking_1  Previous Heart Problems_1  Medication Use_1  Stress Level_2  Stress Level_3  Stress Level_4  Stress Level_5  Stress Level_6  Stress Level_7  Stress Level_8  Stress Level_9  Stress Level_10
0    BMW7812   67    1          208         158/88          72         0               0        0                    0                 4.168189                 6.615001  261404  31.251233            286                                0                    6  Argentina  South America           1                  0         False           False       True                      False             False           False           False           False           False           False           False           False            True            False
1    CZE1114   21    1          389         165/93          98         1               1        1                    1                 1.813242                 4.963459  285768  27.194973            235                                1                    7     Canada  North America           0                  0         False            True       True                       True             False           False           False           False           False           False           False           False           False            False
2    BNI9906   21    0          324         174/99          72         1               0        0                    0                 2.078353                 9.463426  235282  28.176571            587                                4                    4     France         Europe           0                  0          True           False      False                       True              True           False           False           False           False           False           False           False            True            False
3    JLN3497   84    1          383        163/100          73         1               1        0                    1                 9.828130                 7.648981  125640  36.464704            378                                3                    4     Canada  North America           0                  0         False           False       True                       True             False           False           False           False           False           False           False           False            True            False
4    GFO8847   66    1          318          91/88          93         1               1        1                    0                 5.804299                 1.514821  160555  21.809144            231                                1                    5   Thailand           Asia           0                  0         False            True       True                       True             False           False           False           False           False            True           False           False           False            False

In [116]:
# Ajustar para exibir mais colunas no terminal
pd.set_option('display.max_columns', None)  # Mostrar todas as colunas
pd.set_option('display.width', 1000)       # Ajustar a largura da saída

In [117]:
# Exibir as primeiras 10 colunas
print(df_heart.iloc[:, :10].head())

  Patient ID  Age  Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  Family History  Obesity  Alcohol Consumption
0    BMW7812   67    1          208         158/88          72         0               0        0                    0
1    CZE1114   21    1          389         165/93          98         1               1        1                    1
2    BNI9906   21    0          324         174/99          72         1               0        0                    0
3    JLN3497   84    1          383        163/100          73         1               1        0                    1
4    GFO8847   66    1          318          91/88          93         1               1        1                    0

In [118]:
# Exibir da 11ª até a 20ª coluna
print(df_heart.iloc[:, 10:20].head())

   Exercise Hours Per Week  Sedentary Hours Per Day  Income        BMI  Triglycerides  Physical Activity Days Per Week  Sleep Hours Per Day    Country      Continent  Hemisphere
0                 4.168189                 6.615001  261404  31.251233            286                                0                    6  Argentina  South America           1
1                 1.813242                 4.963459  285768  27.194973            235                                1                    7     Canada  North America           0
2                 2.078353                 9.463426  235282  28.176571            587                                4                    4     France         Europe           0
3                 9.828130                 7.648981  125640  36.464704            378                                3                    4     Canada  North America           0
4                 5.804299                 1.514821  160555  21.809144            231                                1                    5   Thailand           Asia           0

In [119]:
# Exibir as primeiras 5 linhas transpostas
print(df_heart.head().T)

                                             0              1          2              3          4
Patient ID                             BMW7812        CZE1114    BNI9906        JLN3497    GFO8847
Age                                         67             21         21             84         66
Sex                                          1              1          0              1          1
Cholesterol                                208            389        324            383        318
Blood Pressure                          158/88         165/93     174/99        163/100      91/88
Heart Rate                                  72             98         72             73         93
Diabetes                                     0              1          1              1          1
Family History                               0              1          0              1          1
Obesity                                      0              1          0              0          1
Alcohol Consumption                          0              1          0              1          0
Exercise Hours Per Week               4.168189       1.813242   2.078353        9.82813   5.804299
Sedentary Hours Per Day               6.615001       4.963459   9.463426       7.648981   1.514821
Income                                  261404         285768     235282         125640     160555
BMI                                  31.251233      27.194973  28.176571      36.464704  21.809144
Triglycerides                              286            235        587            378        231
Physical Activity Days Per Week              0              1          4              3          1
Sleep Hours Per Day                          6              7          4              4          5
Country                              Argentina         Canada     France         Canada   Thailand
Continent                        South America  North America     Europe  North America       Asia
Hemisphere                                   1              0          0              0          0
Heart Attack Risk                            0              0          0              0          0
Diet_Healthy                             False          False       True          False      False
Stress Level_2                           False          False      False          False      False
Stress Level_3                           False          False      False          False      False
Stress Level_4                           False          False      False          False      False
Stress Level_5                           False          False      False          False      False
Stress Level_6                           False          False      False          False       True
Stress Level_7                           False          False      False          False      False
Stress Level_8                           False          False      False          False      False
Stress Level_9                            True          False       True           True      False
Diet_Unhealthy_True                      False           True      False          False       True
Smoking_1_True                            True           True      False           True       True
Previous Heart Problems_1_True           False           True       True           True       True
Medication Use_1_True                    False          False       True          False      False
Stress Level_10_True                     False          False      False          False      False